production:
  adapter: sqlite3
  encoding: utf8
  database: db/sms_production.sqlite3
  timeout: 5000  

development:
  adapter: sqlite3
  encoding: utf8
  database: db/sms_development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: db/sms_test.sqlite3
  timeout: 5000
