# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "administrators", :force => true do |t|
    t.column "login",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "forum_posts", :force => true do |t|
    t.column "user_name",    :string,   :limit => 50, :default => "", :null => false
    t.column "user_id",      :integer
    t.column "speech_id",    :integer
    t.column "subject",      :string,                 :default => "", :null => false
    t.column "body",         :text
    t.column "root_id",      :integer,                :default => 0,  :null => false
    t.column "parent_id",    :integer,                :default => 0,  :null => false
    t.column "lft",          :integer,                :default => 0,  :null => false
    t.column "rgt",          :integer,                :default => 0,  :null => false
    t.column "depth",        :integer,                :default => 0,  :null => false
    t.column "created_at",   :datetime,                               :null => false
    t.column "updated_at",   :datetime,                               :null => false
    t.column "is_anonymous", :boolean
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "speeches", :force => true do |t|
    t.column "date",         :datetime
    t.column "topic",        :string
    t.column "abstract",     :text
    t.column "speaker_id",   :integer
    t.column "attachment",   :string
    t.column "speaker_name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "realname",                  :string
    t.column "role",                      :string
  end

end
